#!/bin/bash
# Dedups and lint a source directory and export optimized pics to a destination directory.

# EDIT
src="$HOME/Pictures/photos" # source dir where original pics are
dst="$HOME/Sync/Photos" # destination dir where optimized pics will be
height="1440" # max height of the converted pic
extension="" # leave empty to not convert and put webp with you want an agressive size reduction and loss of quality

# DON'T EDIT
function findPics { find "$src" -regex '.*\.\(jpg\|jpeg\|png\|webp\)'; }
function convertPic { convert "$1" -resize x$height -strip "$2"; }  

# Dedup and other forms of file linting at source dir
# rmlint don't delete by itself but export a script that does that. When you set the output with -o it don't use the defaults and will work stupidly.
# You have to manuallly tell him everything. And -c and -d are script arguments for delete empty folders and run quiet.
findPics | rmlint - -T "bl,ed,ef,df" -R -PP -v -S "lam" -o "sh:/tmp/rmlint" && /tmp/rmlint -c -d

# Resize images, strip metadata, optionallly convert and export to destination
echo "Exporting lighter images..."
mapfile -t pics < <(findPics)

for path in "${pics[@]}"; do
    file="${path/*\//}"
    # shellcheck disable=SC2086
    if [ $extension ]; then
        convertPic "$path" "$dst/${file/.*/.$extension}" 
    else
        convertPic "$path" "$dst/$file" 
    fi
done

